name: Pawtograder
description:
  An action for automatically submitting and grading student coding submissions
author: Jonathan Bell <jon@jonbell.net>

branding:
  icon: heart
  color: red

inputs:
  grading_server:
    description:
      URL of the grading API server, e.g. https://autograder.ripley.cloud
    required: true
  handout_repo:
    description:
      The name of the handout repo, e.g. khoury-classroom/handout-template. This
      is only used to check if the action is being run in the handout repo, and
      if so, no submission will be created (so your handout built can still be
      green).
    required: false
  regression_test_job:
    description:
      The name of the job to run the regression test on, e.g.
      khoury-classroom/handout-template.
    required: false

outputs:
  score:
    description: The score of the submission

runs:
  using: node20
  main: dist/index.js
