name: CI

on:
  pull_request:
  push:

jobs:
  lint:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: ${{ vars.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_TOKEN }}

      - name: Build
        run: nix build --keep-going

      - name: Test
        run: nix flake check --keep-going
