name: Run the autograder action

on: ['push']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run the autograder action
        uses: ./
        with:
          grading_server: 'https://khoury-classroom-dev.ngrok.pizza'
